name: Release Windows Executable

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13" # 프로젝트의 Python 버전에 맞게 조정하세요.

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --frozen

      - name: Install Playwright Browsers
        run: uv run playwright install --with-deps chromium
        env:
          PLAYWRIGHT_BROWSERS_PATH: 0

      - name: Build with PyInstaller
        run: uv run pyinstaller --noconfirm --onefile --name viral-marketing-reporter ./src/viral_marketing_reporter/main.py

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/viral-marketing-reporter.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
