name: Release Windows Executable

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13" # 프로젝트의 Python 버전에 맞게 조정하세요.

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync --dev

      - name: Install Playwright Browsers
        run: PLAYWRIGHT_BROWSERS_PATH=0 uv run playwright install chromium

      - name: Build with PyInstaller
        run: uv run pyinstaller --name ViralMarketingReporter --noconfirm --clean --windowed --onedir src/viral_marketing_reporter/main.py

      - name: Package application for release
        shell: pwsh
        run: |
          $VERSION = "${{ github.ref_name }}"
          $ZIP_FILENAME = "ViralMarketingReporter-windows-${VERSION}.zip"
          Compress-Archive -Path dist/ViralMarketingReporter -DestinationPath $ZIP_FILENAME
          echo "RELEASE_ZIP_PATH=$ZIP_FILENAME" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.RELEASE_ZIP_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
